version: 0.2

phases:
  pre_build:
    commands:
      - echo pre_build step...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker-compose build 
  
    
