version: 0.2

phases:
  pre_build:
    commands:
      
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - ssh newuser@3.110.124.191 -p docker-compose build  
      - docker-compose up -d 
  
    
