version: 0.2

phases:
  pre_build:
    commands:
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - pwd
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      
 post_build:
    commands:
      - echo Build completed on `date`
      
    
