version: 0.2

phases:
  pre_build:
    commands: 
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 117801723042.dkr.ecr.ap-south-1.amazonaws.com
    
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - pwd
#       - docker build -t codebuilddemo .
      - docker tag codebuilddemo:latest 117801723042.dkr.ecr.ap-south-1.amazonaws.com/codebuilddemo:latest
      - pwd 
      - echo deploy
      - docker-compose up -d
      - ssh newuser@3.110.101.92 -p 1234567  
      - mv . /var/lib/docker
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 117801723042.dkr.ecr.ap-south-1.amazonaws.com/codebuilddemo:latest
      
